(function(){var e=void 0,g=true,i=null,j=false;function k(){return function(){}}function o(a){return function(){return this[a]}}function p(a){return function(){return a}}var q,r=this;
function aa(a){var b=typeof a;if(b=="object")if(a){if(a instanceof Array)return"array";else if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if(c=="[object Window]")return"object";if(c=="[object Array]"||typeof a.length=="number"&&typeof a.splice!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("splice"))return"array";if(c=="[object Function]"||typeof a.call!="undefined"&&typeof a.propertyIsEnumerable!="undefined"&&!a.propertyIsEnumerable("call"))return"function"}else return"null";
else if(b=="function"&&typeof a.call=="undefined")return"object";return b}function ba(a,b,c){return a.call.apply(a.bind,arguments)}function ca(a,b,c){if(!a)throw Error();if(arguments.length>2){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}else return function(){return a.apply(b,arguments)}}
function s(a,b,c){s=Function.prototype.bind&&Function.prototype.bind.toString().indexOf("native code")!=-1?ba:ca;return s.apply(i,arguments)}function da(a){var b=ea;function c(){}c.prototype=b.prototype;a.V=b.prototype;a.prototype=new c;a.prototype.constructor=a};function ga(){for(var a="",b=0;b<16;b++)a+=Math.random();return a}function t(a,b){var c="",d=ha(encodeURIComponent(a));d.splice(b||5,d.length);w(d,function(a,b){var d;d=b;if(d==0)d="A";else{d>>>=0;for(var n="",m;d>0;)m=d%64,n="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/".charAt(m)+n,d>>>=6;d=n}c+=d});return c}
function ha(a){a+=String.fromCharCode(128);for(var b=[1518500249,1859775393,2400959708,3395469782],c=1732584193,d=4023233417,f=2562383102,h=271733878,l=3285377520,n=[],m,B,v,J,K,I=Math.ceil((a.length/4+2)/16),M=[I],y=0,u;y<I;y++){M[y]=[];for(m=0;m<16;m++)M[y][m]=a.charCodeAt(y*64+m*4)<<24|a.charCodeAt(y*64+m*4+1)<<16|a.charCodeAt(y*64+m*4+2)<<8|a.charCodeAt(y*64+m*4+3)}y=(a.length-1)*8;a=I-1;M[a][14]=Math.floor(y/Math.pow(2,32));M[a][15]=y&4294967295;for(y=0;y<I;y++){for(u=0;u<16;u++)n[u]=M[y][u];
for(u=16;u<80;u++)n[u]=(n[u-3]^n[u-8]^n[u-14]^n[u-16])<<1|(n[u-3]^n[u-8]^n[u-14]^n[u-16])>>>31;a=c;m=d;B=f;v=h;J=l;for(u=0;u<80;u++)K=Math.floor(u/20),K=(a<<5|a>>>27)+(K==0?m&B^~m&v:K==1?m^B^v:K==2?m&B^m&v^B&v:m^B^v)+J+b[K]+n[u]&4294967295,J=v,v=B,B=m<<30|m>>>2,m=a,a=K;c=c+a&4294967295;d=d+m&4294967295;f=f+B&4294967295;h=h+v&4294967295;l=l+J&4294967295}return[c,d,f,h,l]}
function ia(a){var b=i;if(a){for(var b=i,a=document.getElementsByTagName("link"),c=0,d=a.length;c<d;++c)if(a[c].rel=="canonical")b=a[c].href,b=b.substring(b.indexOf("/",9));if(b)return b}c=r.location;b=c.pathname+(c.search||"");b=b.replace(/PHPSESSID=[^&]+/,"");a=/&utm_[^=]+=[^&]+/ig;(c=a.exec(c.search))&&(b=b.replace(a,""));a=/\?utm_[^=]+=[^&]+(.*)/i;(c=a.exec(b))&&(b=b.replace(a,c[1]!=""?"?"+c[1]:""));return b}function x(a,b){return function(){a.apply(b,arguments)}}
function z(a,b,c){a.addEventListener?a.addEventListener(b,c,j):a.attachEvent&&a.attachEvent("on"+b,c)}function ja(a,b,c){a.removeEventListener?a.removeEventListener(b,c,j):a.detachEvent&&a.detachEvent("on"+b,c)}function ka(a){a=new Date(+a);return Date.UTC(a.getFullYear(),a.getMonth(),a.getDate())}function A(){return(new Date).getTime()}function C(a){return encodeURIComponent(a)}
function w(a,b){if((!!a&&a.constructor===Object)===g)for(var c in a){if(a.hasOwnProperty(c)&&b(c,a[c])===j)break}else{c=a.length;for(var d=0;d<c;d++)if(b(d,a[d])===j)break}}function D(a){return a===e?0:A()-a}
function la(a,b){var c,d,f="c"+Math.round(Math.random()*1E9);d=250;a+=(a.indexOf("?")>-1?"&":"?")+(c||"callback")+"=_cb_call."+f;c=document.createElement("script");var h=ma(f,c);c.id=f;c.type="text/javascript";c.charset="UTF-8";c.src=a;var l=document.getElementsByTagName("head");if(l=l&&l[0]){var n=r._cb_call||(r._cb_call={});d=setTimeout(na(b,h),d);n[f]=oa(b,h,d);l.appendChild(c)}}function na(a,b){return function(){b();a(e,"TIMEOUT")}}function oa(a,b,c){return function(d){b(c);a(d)}}
function ma(a,b){return function(c){c&&clearTimeout(c);setTimeout(function(){b&&b.parentNode&&b.parentNode.removeChild(b)},0);var d=r._cb_call,f=j;if(d&&(c?delete d[a]:d[a]=pa,w(d,function(){f=g;return j}),!f))try{delete r._cb_call}catch(h){r._cb_call=e}}}function pa(){}
function qa(a,b){if(a===b)return 0;if(a.length===0)return b.length;if(b.length===0)return a.length;for(var c=[],d=0,f=b.length;d<=f;d++)c[d]=[d];for(var h=0,l=a.length;h<=l;h++)c[0][h]=h;for(var n,m,B,d=1;d<=f;d++)for(h=1;h<=l;h++)n=d-1,m=h-1,B=c[n][m],b.charAt(n)==a.charAt(m)?c[d][h]=B:(m=c[d][m]+1,n=c[n][h]+1,B+=2,c[d][h]=Math.min(m,n,B));return c[b.length][a.length]};function E(){this.na=[];this.kb=j;this.Na=this.$=i;this.oa=[];ra(this,r,"onscroll");ra(this,document.body,"onkeydown");ra(this,document.body,"onmousemove");this.F()}E.prototype.F=function(){this.ga={};this.J=0;sa(this);this.ga.onmousemove=A()};function sa(a){a.Ta&&clearInterval(a.Ta);a.gb();a.Ta=setInterval(x(a.gb,a),1E3)}
function ra(a,b,c){var d=b[c]||k();a.oa.push(c);b[c]=function(b){d.apply(this,arguments);if(b&&c=="onkeydown"){var h=b.keyCode?b.keyCode:b.which;if(h==32||h>36&&h<41){a.ga.onscroll=A();return}}a.ga[c]=A();if(a.kb)a.$===i&&a.Sa(),r.clearTimeout(a.Na),a.Na=r.setTimeout(x(a.Sa,a),500)}}E.prototype.Sa=function(){var a=this;this.$=r.setTimeout(function(){r.clearTimeout(a.$);a.$=i},500);for(var b=0,c=this.na.length;b<c;b++)if(typeof this.na[b]==="function")this.na[b]()};
function ta(a,b,c){a=a.ga[b];if(a===e)return j;a=A()-a;return a<=(c||15E3)&&a>=0}E.prototype.gb=function(){var a;a:{a=0;for(var b=this.oa.length;a<b;a++)if(ta(this,this.oa[a],5E3)){a=g;break a}a=j}a&&this.J++};function ua(a){var b=a.J;a.J=0;sa(a);return b};function va(a){var b={};if(a){a.charAt(0)=="?"&&(a=a.substring(1));for(var a=a.replace("+"," "),a=a.split(/[&;]/g),c=0,d=a.length;c<d;c++){var f=a[c].split("=");b[decodeURIComponent(f[0])]=decodeURIComponent(f[1])}}return b}function wa(a,b,c){var d="",f=r.location.href.split("?");f.length&&(f=va(f[1]),b=c||b,f[b]&&(d="&"+a+"="+f[b]));return d};function F(a,b,c){a[b]=a[b]||c}function xa(a,b){for(var c=r[a]||[];c.length;)b(c.shift());r[a]={push:b}}function ya(a,b,c){return a[c]?"&g"+b+"="+encodeURIComponent(a[c]):""};var G={};G.h=function(a){var b=r._sf_async_config;if(!a&&b&&b.noCookies)return i;if(G.h.sa!==e)return G.h.sa;var a=A()+"",c,d;try{if((d=r.localStorage).setItem(a,a),c=d.getItem(a)===a,d.removeItem(a),c)return G.h.sa=d}catch(f){}return G.h.sa=i};G.e=function(a){var b=G.h();if(!b)return"";var c=b.getItem(a+"_expires");return c&&(c=+c,!isNaN(c)&&A()>c)?(G.remove(a),""):b.getItem(a)||""};
G.create=function(a,b,c){var d=G.h();if(d){try{d.setItem(a,b)}catch(f){}b=new Date;b.setTime(A()+c*864E5);try{d.setItem(a+"_expires",b.getTime())}catch(h){}}};G.remove=function(a){var b=G.h();b&&(b.removeItem(a),b.removeItem(a+"_expires"))};var za=(document.location.protocol=="https:"?"https://a248.e.akamai.net/chartbeat.download.akamai.com/102508/":"http://static.chartbeat.com/")+"js/inpage.js";function Aa(){var a=document.createElement("script");a.async=g;a.src=za;var b=document.getElementsByTagName("script")[0];b.parentNode.insertBefore(a,b)}function Ba(a){if(/[\/|\.]chartbeat\.com$/.test(a.origin)){var b=G.h(g),c=String(a.data);b&&c.indexOf("_cb_ip")==0&&(b.setItem("_cb_ip","1"),a.source.postMessage(1,a.origin),Aa())}};var H={e:function(a){a+="=";for(var b=document.cookie.split(";"),c,d=0,f=b.length;d<f;d++){for(c=b[d];c.charAt(0)===" ";)c=c.substring(1,c.length);if(c.indexOf(a)===0)return c.substring(a.length,c.length)}return""},create:function(a,b,c){var d=r._sf_async_config;if(!d||!d.noCookies)d=new Date,d.setTime(A()+c*864E5),document.cookie=a+"="+b+("; expires="+d.toGMTString())+"; path=/"}};H.remove=function(a){H.e(a)&&H.create(a,"",-1)};function L(a){this.ia=a||"";this.Ia=j;Ca(this)}
function Ca(a){if(!H.e("_cb_ls")){var b=G.h()!==i,c=H.e("_SUPERFLY_nosample");c&&w(["","_v_","_p_"],function(b,d){a.create(d+"_SUPERFLY_nosample",c,0.007,g)});var d=H.e("_chartbeat3");d&&(a.create("_v__chartbeat3",d,30,g),H.remove("_chartbeat3"));b&&((b=H.e("_chartbeat2"))&&a.create("_chartbeat2",b,30,g),(b=H.e("_chartbeat_uuniq"))&&a.create("_chartbeat_uuniq",b,30,g),(b=H.e("_chartbeat5"))&&a.create("_chartbeat5",b,6.944444444444445E-4,g));H.create("_cb_ls","1",30)}}
function Da(a){var b=a.Ia;a.Ia=j;return b}L.prototype.create=function(a,b,c,d){a=d?a:this.ia+a;(G.h()?G:H).create(a,b,c);G.h()&&H.create(a,b,c)};L.prototype.update=function(a,b,c,d,f,h){a=d?a:this.ia+a;f=typeof f==="string"?f:"::";d=(d=this.e(a,g))?d.split(f):[];typeof h==="number"&&d.length>=h&&d.splice(0,d.length-h+1);d.push(b);this.create(a,d.join(f),c,g)};
L.prototype.e=function(a,b){var a=b?a:this.ia+a,c=(G.h()?G:H).e(a);if(!c&&G.h()&&(c=H.e(a))&&H.e("_cb_ls")){this.Ia=g;var d;switch(a){case "_SUPERFLY_nosample":d=0.007;break;case "_chartbeat4":d=0.0417;break;case "_cb_cp":d=0.0417;break;default:d=30}G.create(a,c,d)}return c};L.prototype.remove=function(a,b){a=b?a:this.ia+a;(G.h()?G:H).remove(a);G.h()&&H.remove(a)};function Ea(a,b){var c,b=b||"*";c=c||document;if("querySelectorAll"in c)return c.querySelectorAll(b+"["+a+"]");var d=[];c=c.getElementsByTagName(b);for(var f=c.length;f--;)c[f].getAttribute(a)&&d.push(c[f]);return d}function Ia(a,b,c){return a===e?j:c===e&&a.getAttribute(b)||a.getAttribute(b)===c?a:a===document.body?j:Ia(a.parentNode,b,c)}
function Ja(a){var b,c;b="pageYOffset";c="scrollTop";if(a&&(a=Ea("data-cb-scroll-element"))&&a.length)return a[0][c];if(typeof r[b]=="number")return r[b];else if(document.body&&document.body[c])return document.body[c];else if(document.documentElement[c])return document.documentElement[c];return 0}function Ka(){var a=document;return a[a.compatMode==="CSS1Compat"?"documentElement":"body"].clientHeight||0}function N(a){a="scroll"+a;return Math.max(document.body[a],document.documentElement[a])||0};function ea(a){this.b=r._sf_async_config||{};this.nb=x(this.xb,this);this.T=[];this.aa=a;this.f=new L(this.Fb);this.F();this.Za=x(this.Ca,this);z(r,"unload",this.Za);xa("_cbq",x(this.Cb,this))}q=ea.prototype;q.F=function(){this.xa=this.P=0;this.ka=A();this.U=t(O(this,j));this.Ga=g;this.ya=72E5;this.O=this.J=0;this.aa.F();var a=+this.b.sessionLength;if(!isNaN(a))this.ya=a*6E4};
function La(a){if(!a.f.e("_SUPERFLY_nosample"))a.rb?a.Ha():(a.rb=g,!r._sf_async_config&&!r._cbq?(a.Xa=x(a.Ha,a),z(r,"load",a.Xa)):a.Ha())}q.Ha=function(){var a=r._sf_startpt,b=r._sf_endpt;if(typeof a=="number")this.ha=typeof b=="number"?b-a:A()-a;this.K=setInterval(x(this.G,this),15E3);this.G()};
q.G=function(){this.O=ua(this.aa);this.J+=this.O;var a=this.b.reading&&+this.b.reading||this.O>0;this.xa<this.P&&!a?this.xa++:(a?this.P=0:this.ra(),this.xa=0,this.T.push(0),this.T.length>18&&this.T.shift(),this.$a(),A()-this.ka>=this.ya&&clearInterval(this.K))};function Ma(a,b){var c;c=new Image(1,1);c.onerror=a.nb;c.src=b}q.xb=function(){this.T.push(1);for(var a=0,b=0,c=this.T.length;b<c;++b)a+=this.T[b];a<3?(this.Ga=g,this.ra()):(clearInterval(this.K),this.f.create("_SUPERFLY_nosample","1",0.007))};
q.Ca=function(){this.f.update("_cb_cp",this.U,0.0417,j,",")};q.Cb=function(a){this.b[a[0]]=a[1];this.P=0};q.ra=function(){var a=this.P;this.P=a=a?Math.min(a*2,16):1};q.Ib=function(a,b){this.hb=r.location.protocol+"//"+this.b.domain+this.b.path;this.b.path=a;b&&(this.b.title=b);clearInterval(this.K);this.F();La(this)};function Na(a){if(a.hb)return g;a=(document.referrer||"").indexOf("://"+r.location.host+"/");return a!=-1&&a<9}function Oa(a){return encodeURIComponent(a.hb||document.referrer||"")}
function Pa(a){a=a.b.title.slice(0,100);return encodeURIComponent(a)}function O(a,b){var c=r.navigator,d=r.window.screen,f=[c.userAgent,c.platform,(new Date).getTimezoneOffset(),d.width+d.height+d.colorDepth];w(c.plugins,function(a,b){f.push(b.name+b.description+b.filename+b[0].type)});if(b===j)c=r.performance,f=f.concat([c&&c.now?c.now():"",Oa(a),document.title,r.location.href,A(),N("Width"),N("Height"),ga()]);return f.join()}q.va=function(){ja(r,"load",this.Xa);ja(r,"unload",this.Za);clearInterval(this.K)};function P(a){ea.call(this,a);z(document.body,"click",x(this.wb,this))}da(P);q=P.prototype;
q.F=function(){P.V.F.call(this);this.pa=i;for(var a=this.b,b=document.getElementsByTagName("script"),c=0,d=b.length;c<d;++c)if(b[c].src.match(/chartbeat.js/)){b=va(b[c].src.split("?")[1]);F(a,"uid",b.uid);F(a,"domain",b.domain);break}a=r.location;F(this.b,"pingServer","ping.chartbeat.net");F(this.b,"title",document.title);F(this.b,"domain",a.host);F(this.b,"path",ia(!!this.b.useCanonical));this.wa=a.host.replace(/^www\./,"");this.b.domain=this.b.domain.replace(/^www\./,"");var a=(this.f.e("_chartbeat2",
g)||"").split("."),b=A(),c=b-+(a[1]||0),f="1",h=a&&+a[2],d=a&&a[3];if(a&&h&&d)if(f=Math.abs((ka(b)-ka(h))/864E5)){f=Math.min(f,16)-1;for(h="";f--;)h+=0;f=(d+h+"1").slice(-16)}else f=d;d=f;this.Ba=a[0]&&c>18E5?0:1;a[0]||(a[0]=t(O(this,j),3),a[1]=b);a[2]=b;a[3]=d;this.la=a[0];this.L=a.join(".");this.f.create("_chartbeat2",this.L,30,g);this.b.utoken=this.la;var l;b=+a[1];c=+a[2];if((a=a[3])&&b&&c)l=(Math.min((Math.abs((ka(c)-ka(b))/864E5)||0)+1,16,a.length)-1).toString(16),l+=("0000"+parseInt(a,2).toString(16)).slice(-4);
this.Ra=l;r.postMessage&&z(r,"message",x(this.ob,this));l=this.f.e("_chartbeat_uuniq")==="3";this.f.create("_chartbeat_uuniq","3",30);l||Ma(this,"//ping.chartbeat.net/uuniq?u="+this.la+"&u2="+t(O(this,g)))};q.jb=function(a){this.pa=a};q.Ca=function(){P.V.Ca.call(this);this.O=ua(this.aa);this.J+=this.O;this.f.update("_chartbeat4",["t="+this.U,"E="+this.J,"x="+Ja(!!this.b.scrollElement),"c="+Math.round((A()-this.ka)/600)/100,"y="+N("Height"),"w="+Ka()].join("&"),0.0417)};
q.$a=function(){var a=this.b,b=Ja(!!a.scrollElement),c=Math.round((A()-this.ka)/600)/100,d=0,f=0,h=0;ta(this.aa,"onkeydown")?f=1:this.b.reading&&+this.b.reading||this.O>0||c<0.09?d=1:h=1;var l="",n="",m="",B="",v=Na(this);if(this.Ga){this.Ga=j;var l=(v?"&v=":"&r=")+Oa(this),n="&i="+Pa(this),J=this.b.hudTrackable;J!==e&&(m="&L="+(J?"1":"0"));if(v&&(v=Qa(this)))l="&v="+encodeURIComponent(v.path),B="&K="+v.left+"::"+v.top,v.Va>1&&(B+="&l1="+v.Va)}var v=this.ha?"&b="+this.ha:"",J=this.pa?"&A="+this.pa:
"",K=this.Ra?"&f="+this.Ra:"",I=this.f.e("_cb_cp"),I=I?"&D="+I:"";this.f.remove("_cb_cp");var M="",y=this.f.e("_chartbeat4");y&&(w(y.split("::"),function(a,b){M+="&z="+encodeURIComponent(b)}),this.f.remove("_chartbeat4"));var y=[],u;for(u in a)u.charAt(0)=="_"&&y.push(u+"="+a[u]);Ma(this,(r.location.protocol||"http:")+"//"+a.pingServer+"/ping?h="+encodeURIComponent(a.domain)+"&p="+encodeURIComponent(a.path)+"&u="+this.la+"&d="+encodeURIComponent(this.wa)+"&g="+a.uid+ya(a,0,"sections")+ya(a,1,"authors")+
(a.noCookies?"":"&n="+this.Ba)+K+"&c="+c+"&x="+b+"&y="+N("Height")+"&o="+N("Width")+"&w="+Ka()+"&j="+Math.round((this.P+2)*15E3/1E3)+"&R="+d+"&W="+f+"&I="+h+"&E="+this.J+"&e="+this.O+l+B+v+J+wa("C","utm_campaign",a.campaignTag)+wa("M","utm_medium",a.mediumTag)+"&t="+this.U+"&V=23"+I+M+n+m+(Da(this.f)?"&l=1":"")+(y.length?"&"+y.join("&"):"")+"&_")};
q.ob=function(a){var b=this.b;if(a.origin==="http://"+(b.playerdomain||this.wa)){var c=a.data;if(typeof c=="string"&&c.indexOf("cbqpush::")===0){if(a=c.split("::"),a.length==3)a[1].indexOf("_")===0&&(b[a[1]]=a[2]),this.P=0}else c=="cbdata?"&&(b="domain="+encodeURIComponent(b.domain)+"&path="+encodeURIComponent(b.path)+"&title="+Pa(this)+"&referrer="+Oa(this)+"&internal="+(Na(this)?"1":"0")+"&subdomain="+encodeURIComponent(this.wa)+"&utoken="+this.la,a.source.postMessage(b,"*"))}};
q.wb=function(a){var b,c;if(a=a||window.event){c=a.target||a.srcElement;if(c.tagName!=="A")if(c.parentNode)if(c.parentNode.tagName==="A")c=c.parentNode;else if(c.parentNode.parentNode&&c.parentNode.parentNode.tagName==="A")c=c.parentNode.parentNode;else return;else return;a=c.href||"";a=a.replace(/-{2,}/g,"-");b=a;var d="",f="";if(b){var f=document.createElement("a"),h=r.location;b.indexOf("http")!==0&&b.indexOf("javascript")!==0&&(b=h.protocol+b);f.href=b;d=f.hostname;f=f.protocol;if(d==="")d=h.hostname;
if(f==="")f=h.protocol;f==="javascript:"&&(d="")}if(!(d!==r.location.hostname||f==="javascript:")){b=c;d=b.offsetLeft;c=b.offsetTop;h=j;for(f=b.offsetParent;b&&b!==e&&b!==document.body;){if(b===f)d+=b.offsetLeft,c+=b.offsetTop,f=b.offsetParent;var l=b,n=e;n=r.getComputedStyle?(l=r.getComputedStyle(l,i))&&(l.position||l.getPropertyValue("position")):l.currentStyle?l.currentStyle.position:l.style&&l.style.position;if((n||"")==="fixed"){h=g;break}b=b.parentElement}h&&(d+=0,c+=0);b=d;this.f.update("_chartbeat5",
[b,c,encodeURIComponent(this.b.path),encodeURIComponent(a)].join(","),6.944444444444445E-4,j,e,5)}}};
function Qa(a){var b=a.f.e("_chartbeat5");if(!b)return i;var b=b.split("::"),c=b.length,d,f;if(c===1)d=b[0].split(","),f=0;else{var h,l=r.location.href;w(b,function(a,b){var c=b.split(","),v=qa(l,decodeURIComponent(c[3]));if(v===0)return d=c,f=a,j;if(h===e||v<h)h=v,d=c,f=a})}b.splice(f,1);a.f.create("_chartbeat5",b.join("::"),6.944444444444445E-4);return{left:d[0],top:d[1],path:decodeURIComponent(d[2]),Va:c}};function R(a){this.fa=e;this.g=g;this.bb=this.Oa=-1;this.I=i;this.a=a;this.c=j;this.Da=g;this.d=A();this.Ea="";for(var a=window.experienceJSON.data.configuredProperties.plugins.list.split(" "),b=a.length,c=0;c<b;c++){var d=a[c];if(d.indexOf("chartbeat")>=0||d.indexOf("localhost")>=0){this.Ea=d;break}}if(this.Ea&&(a=va(this.Ea),this.fa=a.domain,a=a.uid,!window._cbq))window._cbq=[],a&&window._cbq.push(["uid",a]),this.fa&&window._cbq.push(["domain",this.fa]);a=window.brightcove;this.a=a.api.getExperience();
b=this.a.getModule(a.api.modules.APIModules.EXPERIENCE);b.getReady()?this.Ya():b.addEventListener(a.player.events.ExperienceEvent.TEMPLATE_READY,s(this.Ya,this))}q=R.prototype;
q.Ya=function(){this.g=g;var a=window.brightcove,b=this.a.getModule(a.api.modules.APIModules.VIDEO_PLAYER),c=this;b.getVideoDuration(function(a){c.Oa=a});b.getCurrentVideo(function(a){c.I=a});a=a.api.events.MediaEvent;b.addEventListener(a.PROGRESS,s(this.yb,this));b.addEventListener(a.STOP,s(this.zb,this));b.addEventListener(a.COMPLETE,s(this.ub,this));b.addEventListener(a.BEGIN,s(this.m,this))};q.yb=function(a){this.bb=a.position;this.N=this.Da=j};q.zb=function(){this.Da=g};
q.ub=function(){this.N=g};q.m=function(){this.N=j;if(!this.c)this.c=g};q.B=o("g");q.w=function(){var a="";this.I&&(a=this.I.displayName);return a};q.k=function(){var a="";this.I&&(a="video@"+this.fa+"/"+this.I.id);return a};q.j=p("ct");q.n=p("");q.z=o("Oa");q.u=function(){return!this.c?"s1":this.N?"s4":this.Da?"s3":"s2"};q.r=o("bb");q.q=p(-1);q.v=function(){var a="";this.I&&(a=this.I.thumbnailURL);return a};q.s=k();q.A=function(){return isNaN(this.d)?0:D(this.d)};
q.l=function(){return this.c?D(this.d):-1};q.C=p(-1);q.o=k();q.t=function(){var a;this.I&&(a=this.I.tags);return a};q.p=p("unkn");R.prototype.isReady=R.prototype.B;R.prototype.getTitle=R.prototype.w;R.prototype.getVideoPath=R.prototype.k;R.prototype.getContentType=R.prototype.j;R.prototype.getAdPosition=R.prototype.n;R.prototype.getTotalDuration=R.prototype.z;R.prototype.getState=R.prototype.u;R.prototype.getCurrentPlayTime=R.prototype.r;R.prototype.getBitrate=R.prototype.q;
R.prototype.getThumbnailPath=R.prototype.v;R.prototype.getPlayerType=R.prototype.s;R.prototype.getViewStartTime=R.prototype.A;R.prototype.getViewPlayTime=R.prototype.l;R.prototype.getViewAdPlayTime=R.prototype.C;R.prototype.getAuthors=R.prototype.o;R.prototype.getSections=R.prototype.t;R.prototype.getAutoplayType=R.prototype.p;R.verify=function(a){return a===window.brightcove};function S(){this.a=window.flowplayer();this.c=this.g=j;this.d=A();this.M=this.Q=e;this.fb=this.Ja="";this.Aa=e;this.H()}var Ra=/url\(['"]?([^'"\)]*)['"]?\)/;q=S.prototype;
q.Qa=function(){var a=this.k(),b=Ea("name","param"),c=e;w(b,function(b,d){if(d.attributes.name.value==="flashvars"&&d.value.indexOf(a)!==-1)return c=d,j});if(c===e)return j;b=Ia(c,"data-swf");if(b===j)return j;var d=b.style.background;if(d){if(d=d.match(Ra))this.Ja=d[1]}else this.Ja=b.attributes.poster&&b.attributes.poster.value;this.fb=b.title;this.Aa!==e&&clearInterval(this.Aa);return g};
q.H=function(){this.a.Lb?this.D():this.a.bind("ready",s(this.D,this));this.a.bind("resume",s(this.m,this));this.a.Kb&&this.m()};q.D=function(){if(this.Qa()===j)this.Aa=setInterval(s(this.Qa,this),1E3);this.g=g};q.m=function(){if(!this.c)this.c=g};q.B=o("g");q.w=o("fb");q.k=function(){return this.a.video.url};q.j=p("ct");q.n=p("");q.z=function(){return this.a.video.duration};q.u=function(){return!this.c?"s1":this.a.Jb?"s4":this.a.paused?"s3":"s2"};q.r=function(){return this.a.video.time};q.q=p(-1);
q.v=o("Ja");q.s=k();q.p=k();q.A=function(){return isNaN(this.d)?0:D(this.d)};q.l=function(){return this.c?D(this.d):-1};q.C=p(-1);q.t=o("Q");q.o=o("M");S.prototype.isReady=S.prototype.B;S.prototype.getTitle=S.prototype.w;S.prototype.getVideoPath=S.prototype.k;S.prototype.getContentType=S.prototype.j;S.prototype.getAdPosition=S.prototype.n;S.prototype.getTotalDuration=S.prototype.z;S.prototype.getState=S.prototype.u;S.prototype.getCurrentPlayTime=S.prototype.r;S.prototype.getBitrate=S.prototype.q;
S.prototype.getThumbnailPath=S.prototype.v;S.prototype.getPlayerType=S.prototype.s;S.prototype.getAutoplayType=S.prototype.p;S.prototype.getViewStartTime=S.prototype.A;S.prototype.getViewPlayTime=S.prototype.l;S.prototype.getViewAdPlayTime=S.prototype.C;S.prototype.getSections=S.prototype.t;S.prototype.getAuthors=S.prototype.o;S.verify=function(){return!!window.flowplayer};function T(a){this.a=a;this.c=this.g=j;this.d=A();this.M=this.Q=e;this.H()}q=T.prototype;q.H=function(){this.a.readyState>2&&this.D();this.a.currentTime>0&&!this.a.paused&&!this.a.ended&&this.m();this.a.addEventListener("canplay",s(this.D,this));this.a.addEventListener("playing",s(this.m,this))};q.D=function(){this.g=g};q.m=function(){this.c=g};q.B=o("g");q.w=function(){return this.a.attributes.title&&this.a.attributes.title.value||""};q.k=function(){return this.a.currentSrc||""};q.j=p("ct");
q.n=p("");q.z=function(){return Math.round(this.a.duration===-1||isNaN(this.a.duration)?-1:this.a.duration*1E3)};q.u=function(){return!this.c?"s1":this.a.ended?"s4":this.a.paused?"s3":"s2"};q.W=function(a){return a===e?0:A()-a};q.Wa=k();q.r=function(){return Math.round(this.a.currentTime===-1||isNaN(this.a.currentTime)?-1:this.a.currentTime*1E3)};q.q=p(-1);q.v=function(){return this.a.poster||""};q.s=k();q.p=k();q.A=function(){return isNaN(this.d)?0:this.W(this.d)};
q.l=function(){return this.c?this.W(this.d):-1};q.C=p(-1);q.t=o("Q");q.o=o("M");T.prototype.isReady=T.prototype.B;T.prototype.getTitle=T.prototype.w;T.prototype.getVideoPath=T.prototype.k;T.prototype.getContentType=T.prototype.j;T.prototype.getAdPosition=T.prototype.n;T.prototype.getTotalDuration=T.prototype.z;T.prototype.getState=T.prototype.u;T.prototype.getCurrentPlayTime=T.prototype.r;T.prototype.getBitrate=T.prototype.q;T.prototype.getThumbnailPath=T.prototype.v;T.prototype.getPlayerType=T.prototype.s;
T.prototype.getAutoplayType=T.prototype.p;T.prototype.getViewStartTime=T.prototype.A;T.prototype.getViewPlayTime=T.prototype.l;T.prototype.getViewAdPlayTime=T.prototype.C;T.prototype.getSections=T.prototype.t;T.prototype.getAuthors=T.prototype.o;T.verify=function(a){return a instanceof HTMLElement&&a.nodeName==="VIDEO"};function U(a){this.a=a();this.c=this.N=this.g=j;this.d=A();this.H()}q=U.prototype;q.H=function(){this.a.onReady(s(this.D,this));this.a.onTime(s(this.Ab,this));this.a.onComplete(s(this.Bb,this))};q.D=function(){this.g=g};q.Ab=function(){this.a.getDuration();this.N=j;if(!this.c)this.c=g};q.Bb=function(){this.N=g};q.B=function(){return this.g||this.a.getState()!==e};q.w=function(){var a=Sa(this);return!a?"":a.title};
function Sa(a){if(a.a.getPlaylistIndex===e)return a.a.getPlaylistItem();var b=a.a.getPlaylist();if(!b)return i;var c=b.length,a=a.a.getPlaylistIndex();return c===0||c<=a?i:b[a]}q.k=function(){var a=Sa(this);return!a?"":a.file};q.j=p("ct");q.n=p("");q.z=function(){var a=this.a.getDuration();if(a>0)return Math.round(a*1E3)};q.u=function(){if(!this.c)return"s1";var a=this.a.getState();return this.N?"s4":a==="PAUSED"?"s3":"s2"};q.r=function(){return this.a.getPosition()};q.q=p(-1);
q.v=function(){var a=Sa(this);return!a?"":a.image};q.s=k();q.A=function(){return isNaN(this.d)?0:D(this.d)};q.l=function(){return this.c?D(this.d):-1};q.C=p(-1);q.o=k();q.t=k();q.p=p("unkn");U.prototype.isReady=U.prototype.B;U.prototype.getTitle=U.prototype.w;U.prototype.getVideoPath=U.prototype.k;U.prototype.getContentType=U.prototype.j;U.prototype.getAdPosition=U.prototype.n;U.prototype.getTotalDuration=U.prototype.z;U.prototype.getState=U.prototype.u;U.prototype.getCurrentPlayTime=U.prototype.r;
U.prototype.getBitrate=U.prototype.q;U.prototype.getThumbnailPath=U.prototype.v;U.prototype.getPlayerType=U.prototype.s;U.prototype.getViewStartTime=U.prototype.A;U.prototype.getViewPlayTime=U.prototype.l;U.prototype.getViewAdPlayTime=U.prototype.l;U.prototype.getAuthors=U.prototype.o;U.prototype.getSections=U.prototype.t;U.prototype.getAutoplayType=U.prototype.p;U.verify=function(a){return a===window.jwplayer};function V(a){this.Ma=e;this.a=a;this.Ua=e;this.g=j;this.S=e;this.qa=this.c=j;this.M=this.Q=this.ba=this.d=e;this.Ma=r.OO;this.Ua=this.a.mb;this.d=A();this.H()}q=V.prototype;
q.H=function(){var a=this.Ua,b=this.Ma.EVENTS;a.subscribe(b.CONTENT_TREE_FETCHED,"OoyalaStrategyPlugin",s(this.D,this));a.subscribe(b.WILL_PLAY_ADS,"OoyalaStrategyPlugin",s(this.tb,this));a.subscribe(b.PLAYING,"OoyalaStrategyPlugin",s(this.m,this));a.subscribe(b.ADS_PLAYED,"OoyalaStrategyPlugin",s(this.sb,this));a.subscribe(b.METADATA_FETCHED,"OoyalaStrategyPlugin",s(this.vb,this));a.subscribe(b.EMBED_CODE_CHANGED,"OoyalaStrategyPlugin",s(this.Wa,this))};q.D=function(){this.g=g};
q.tb=function(){var a=this.a.getPlayheadTime(),b=this.a.getDuration();isNaN(a)&&(a=0);this.S=a===0?"a1":Ta(a,b)?"a3":"a2"};q.m=function(){if(this.j()==="ad")this.ba=A(),this.qa=g;this.c=g};q.sb=function(){this.S=e};q.vb=k();q.B=o("g");q.w=function(){var a=this.a.getItem();return a?a.title:""};q.k=function(){return(this.a.getItem()||{}).embedCode||""};q.j=function(){return this.S===e?"ct":"ad"};q.n=function(){return this.S?this.S:""};
q.z=function(){var a=this.a.getDuration();return a===-1||isNaN(a)?-1:a*1E3};q.u=function(){if(!this.c)return"s1";if(this.a.getState()==="paused")return"s3";var a=this.a.getPlayheadTime(),b=this.a.getDuration();return Ta(a,b)?"s4":"s2"};function Ta(a,b){return a===b||Math.floor(a)===Math.floor(b)||Math.ceil(a)===Math.ceil(b)||Math.ceil(a)===Math.floor(b)||Math.floor(a)===Math.ceil(b)}q.W=function(a){return a===e?0:A()-a};q.Wa=function(){this.ba=this.S=e};
q.r=function(){var a=this.a.getPlayheadTime();return a===-1||isNaN(a)?-1:a*1E3};q.q=function(){return this.a.getTargetBitrate()};q.v=function(){var a=this.a.getItem();return a?a.promo:""};q.s=k();q.p=k();q.A=function(){return isNaN(this.d)?0:this.W(this.d)};q.l=function(){return this.c||this.qa?this.W(this.d):-1};q.C=function(){return this.qa&&this.ba?this.W(this.ba):-1};q.t=o("Q");q.o=o("M");V.prototype.isReady=V.prototype.B;V.prototype.getTitle=V.prototype.w;V.prototype.getVideoPath=V.prototype.k;
V.prototype.getContentType=V.prototype.j;V.prototype.getAdPosition=V.prototype.n;V.prototype.getTotalDuration=V.prototype.z;V.prototype.getState=V.prototype.u;V.prototype.getCurrentPlayTime=V.prototype.r;V.prototype.getBitrate=V.prototype.q;V.prototype.getThumbnailPath=V.prototype.v;V.prototype.getPlayerType=V.prototype.s;V.prototype.getAutoplayType=V.prototype.p;V.prototype.getViewStartTime=V.prototype.A;V.prototype.getViewPlayTime=V.prototype.l;V.prototype.getViewAdPlayTime=V.prototype.C;
V.prototype.getSections=V.prototype.t;V.prototype.getAuthors=V.prototype.o;V.verify=function(a){return a.hasOwnProperty("mb")&&a.hasOwnProperty("subscribe")&&a.hasOwnProperty("modules")&&a.hasOwnProperty("adPlaying")};function W(a,b,c){this.a=a;this.Gb=b;this.Y=window.location!=window.parent.location;this.ab=j;this.Hb=A();this.Fb="_v_";ea.call(this,c)}da(W);var Ua=r.QUICK_TEST?1E4:6E4,Va="autoDetect",Wa={};q=W.prototype;
q.F=function(){this.Ba=(this.L=this.f.e("_chartbeat3"))?0:1;this.ib=this.eb=g;this.ua=j;this.ja=this.Fa=this.Pa=this.R=e;this.X=15E3;this.ca=e;this.Db=this.Ka=this.La=this.da=this.ea=0;var a=r.location;this.cb=j;F(this.b,"pingServer","ping.chartbeat.net");F(this.b,"title",document.title);F(this.b,"domain",a.host);F(this.b,"path",ia(!!this.b.useCanonical));if(!this.L||this.L.length===0)this.L=t(O(this,j),3);this.f.create("_chartbeat3",this.L,30);(a=this.Gb)&&typeof a==="function"?(this.i=new a(this.a),
a=g):a=j;if(a){this.Pa=setInterval(x(this.lb,this),1E3);if(this.Y===g)this.za=x(this.pb,this),z(window,"message",this.za),this.ca=setInterval(this.Eb,1E3);W.V.F.call(this)}};q.ra=k();
q.G=function(){if(this.i){if(!this.ib)return A()-this.ka>=this.ya&&clearInterval(this.R),W.V.G.call(this);if(this.i.isReady())this.ua=this.ib=j,this.Fa=Xa(this),Ya(this),this.R=setInterval(x(this.ta,this),100),W.V.G.call(this);else if(!this.ua){this.ua=g;if(this.Db++>150)throw"Error: Video strategy never reported its ready state";clearInterval(this.K);this.K=setInterval(x(this.G,this),100)}}};
q.$a=function(){if(this.i){var a=this.b,b=this.i,c=b.getState(),d=b.getVideoPath(),f=this.Y?[]:r._cbq||(r._cbq=[]),h=b.getViewAdPlayTime(),l=b.getViewStartTime(),n=b.getViewPlayTime(),m=b.getThumbnailPath(),B=b.getAutoplayType?b.getAutoplayType():e,h=h===-1?"":h/1E3,l=l===-1?-1:l/1E3,n=n===-1?-1:n/1E3,m=m?encodeURIComponent(m):e,v=this.f.e("_cb_cp"),v=v?"&D="+v:"";this.f.remove("_cb_cp");if(!Wa.path||Wa.path===d||c==="s2"&&Wa.state!=="s2")switch(Wa={path:d,state:c},f.push(["_vi",C(b.getTitle())]),
f.push(["_vp",d]),f.push(["_vdd",encodeURIComponent("video@"+(a.videodomain||a.domain))]),f.push(["_vap",b.getAdPosition()]),f.push(["_vs",b.getState()]),f.push(["_vt",b.getContentType()]),f.push(["_vtn",C(b.getThumbnailPath())]),f.push(["_vd",b.getTotalDuration()]),b.getState()){case "s1":case "s2":case "s3":f.push(["R","1"]);break;case "s4":f.push(["R","0"])}var a=this.b,d=this.i,J=r.location,K=encodeURIComponent("video@"+(a.videodomain||a.domain)),I="",M=this.ha?"&b="+this.ha:"",y=this.b.useSubDomains===
j?this.b.path:Za(this)+this.b.path,u=d.getSections&&d.getSections(),fa=d.getAuthors&&d.getAuthors(),Q=ya(a,0,"sections"),Z=ya(a,1,"authors"),u=u===e?Q:"&g0="+u.join(","),fa=fa===e?Z:"&g1="+fa.join(","),Z="",Q=this.i.getVideoPath();if(this.ja===e)this.ja=Q;else if(Q!=this.ja)Z=X("D",this.U),this.U=t(O(this,j)),this.ja=Q,this.Ka=this.La=this.da=this.ea=0;if(this.eb||Z||this.Y===g&&this.ab===j)this.eb=j,I=(Na(this)?"&v=":"&r=")+Oa(this);this.La+=this.ea;this.ea=0;this.Ka+=this.da;this.da=0;Ya(this);
var Fa=Q="",Ga="",Ha="";if(!this.Y===g||this.cb===g)Q="&_vi="+Pa(this),Fa="&_vp="+encodeURIComponent(y),Ga="&_vh="+C(Za(this)),Ha="&_vdd="+encodeURIComponent(a.domain);b=(J.protocol||"http:")+"//"+a.pingServer+"/ping?h="+K+"&g="+a.uid+"&p="+C(d.getVideoPath())+"&i="+C(d.getTitle())+u+fa+"&u="+this.L+"&t="+this.U+"&x=0&y=0&V=23&n="+this.Ba+M+I+Z+X("_vd",d.getTotalDuration())+Q+Fa+Ga+Ha+"&_vt="+b.getContentType()+X("_vap",b.getAdPosition())+X("_vs",c)+X("_vbr",b.getBitrate())+X("_vvs",l)+X("_vpt",b.getCurrentPlayTime())+
X("_vvsp",n)+X("_vasp",h)+X("_vtn",m)+X("_vaup",B||"unkn")+X("_vplt",this.b.video_type)+X("_vce",this.Ka)+X("c",Math.round(D(this.Hb)/600)/100)+"&W=0&R="+(c==="s2"?"1":"0")+"&I="+(c!=="s2"?"1":"0")+"&E="+this.La+"&j="+(this.X/1E3+15)+v+(Da(this.f)?"&l=1":"")+"&_";if(this.Y===g){c=0;for(h=f.length;c<h;c++)window.top.postMessage("cbqpush::"+f[c].join("::"),"*")}Ma(this,b)}};function X(a,b){return b!==e&&b!==""?"&"+a+"="+b:""}
function Za(a){return a.b.subdomain?a.b.subdomain:r.location.host.replace(/^www\./,"")}q.ta=function(){var a=Xa(this);if(this.Fa!=a)this.Fa=a,Ya(this),this.G()};function Ya(a){var b=a.X;a.X=$a(a)===g?5E3:a.i.getState()==="s1"?Ua:15E3;if(b!=a.X)b=a.X,clearInterval(a.K),a.K=setInterval(x(a.G,a),b)}function Xa(a){return a.i.getState()+a.i.getAdPosition()}function $a(a){return a.i.getState()==="s2"||a.i.getAdPosition()!==""&&a.i.getViewAdPlayTime!==-1}
q.lb=function(){$a(this)===g&&(this.ea+=1,this.i.getContentType()==="ct"&&(this.da+=1))};q.Eb=function(){window.parent.postMessage("cbdata?","*")};
q.pb=function(a){if(a.source===window.parent){var b=a.data;if(a.data.indexOf("domain=")===0){this.cb=g;for(var a={domain:g,path:g,title:g,referrer:g,internal:g,subdomain:g,token:g},b=b.split("&"),c=0,d=b.length;c<d;c++){var f=b[c].split("="),h=f[0],f=f[1];a[h]&&(this.b[h]=decodeURIComponent(f))}ja(window,"message",this.za);clearInterval(this.ca);this.ca=e;this.ab=g;this.G()}}};q.va=function(){ja(window,"message",this.za);clearInterval(this.ca);clearInterval(this.Pa);clearInterval(this.R);W.V.va.call(this)};function Y(a){this.a=a;this.g=g;this.c=j;this.d=A();this.Z=this.R=this.M=this.Q=e;ab(this,$(this));this.H()}q=Y.prototype;q.H=function(){this.R=setInterval(s(this.ta,this),100);this.a.getPlayerState()>-1&&this.m()};q.ta=function(){if(this.a.getPlayerState()===1)clearInterval(this.R),this.R=e,this.m()};q.D=function(){this.g=g};q.m=function(){if(!this.c)this.c=g};function $(a){var b;return(b=(a=a.a.getVideoUrl())&&a.match(/[?&]v=([^&]+)/),a=b)&&a[1]}
function ab(a,b){la("//gdata.youtube.com/feeds/api/videos/"+b+"?v=2&alt=json",x(function(a){if(b==$(this))this.Z=a?{id:b,title:a&&a.entry&&a.entry.title&&a.entry.title.$t||""}:{id:b,title:""}},a))}q.B=function(){return this.g&&!!this.Z};q.w=function(){return this.Z&&this.Z.id===$(this)?this.Z.title:""};q.k=function(){return $(this)||this.a.getVideoUrl()};q.j=p("ct");q.n=p("");q.z=function(){var a=this.a.getDuration();return typeof a==="number"?a*1E3:a};
q.u=function(){if(!this.c)return"s1";var a=this.a.getPlayerState();return a===0?"s4":a===2?"s3":"s2"};q.r=function(){return this.a.getCurrentTime()};q.q=p(-1);q.v=function(){return"http://img.youtube.com/vi/"+$(this)+"/default.jpg"};q.s=k();q.p=k();q.A=function(){return isNaN(this.d)?0:D(this.d)};q.l=function(){return this.c?D(this.d):-1};q.C=p(-1);q.t=o("Q");q.o=o("M");Y.prototype.isReady=Y.prototype.B;Y.prototype.getTitle=Y.prototype.w;Y.prototype.getVideoPath=Y.prototype.k;
Y.prototype.getContentType=Y.prototype.j;Y.prototype.getAdPosition=Y.prototype.n;Y.prototype.getTotalDuration=Y.prototype.z;Y.prototype.getState=Y.prototype.u;Y.prototype.getCurrentPlayTime=Y.prototype.r;Y.prototype.getBitrate=Y.prototype.q;Y.prototype.getThumbnailPath=Y.prototype.v;Y.prototype.getPlayerType=Y.prototype.s;Y.prototype.getAutoplayType=Y.prototype.p;Y.prototype.getViewStartTime=Y.prototype.A;Y.prototype.getViewPlayTime=Y.prototype.l;Y.prototype.getViewAdPlayTime=Y.prototype.C;
Y.prototype.getSections=Y.prototype.t;Y.prototype.getAuthors=Y.prototype.o;Y.verify=function(a){return typeof a.getDuration==="function"&&typeof a.getVideoUrl==="function"&&typeof a.getVideoEmbedCode==="function"};function bb(){r._cbv_strategies||(r._cbv_strategies=[]);r._cbv_strategies.push(V);r._cbv_strategies.push(T);r._cbv_strategies.push(S);r._cbv_strategies.push(Y);r._cbv_strategies.push(U);r._cbv_strategies.push(R);this.ma=[];this.b=r._sf_async_config||{};xa("_cbv",x(this.qb,this));if(this.b[Va]!==j)if(window.jwplayer)window._cbv.push(window.jwplayer);else if(window.flowplayer)window._cbv.push(window.flowplayer);else if(window.brightcove)window._cbv.push(window.brightcove);else for(var a=document.getElementsByTagName("video"),
b=0;b<a.length;b++)window._cbv.push(a[b])}bb.prototype.qb=function(a){if(aa(a)=="array"&&typeof a[0]=="string"){var b=a[0];if(b==="autoDetectYouTubeIframes"){cb();return}else if(b==="removePlayer"){db(this,a[1]);return}}for(var b=j,c=r._cbv_strategies,d=0,f=c.length;d<f;d++){var h=c[d];if(h.verify(a)===g){b=h;break}}b===j||eb(this,a,b)};function db(a,b){var c=a.ma,d=r.pSUPERFLY_video;w(a.ma,function(a,d){b===d&&c.splice(a,1)});w(d,function(a,c){c.a===b&&d.splice(a,1)[0].va()})}
function eb(a,b,c){var d=j;w(a.ma,function(a,c){if(b===c)return d=g,j});d||(c=new W(b,c,new E),r.pSUPERFLY_video.push(c),La(c),a.ma.push(b))}
function cb(){function a(){function a(b){r._cbv.push(b.target)}var b=r.YT.Player,f=document.getElementsByTagName("iframe"),h,l,n,m;for(h=0,l=f.length;h<l;h++)m=(n=f[h].src)&&n.indexOf("www.youtube.com/embed/"),n&&m>=0&&m<9&&new b(f[h],{events:{onReady:a}})}if(r.YT&&r.YT.Player)a();else{var b=r.onYouTubeIframeAPIReady;r.onYouTubeIframeAPIReady=function(){if(b){try{b.apply(r,arguments)}catch(c){}a()}}}};if(window.location==window.parent.location&&!r.pSUPERFLY){var fb=new P(new E);r.pSUPERFLY=fb;P.prototype.virtualPage=P.prototype.Ib;P.prototype.activity=P.prototype.jb;La(fb);var gb=G.h(g);gb&&(z(r,"message",Ba),gb.getItem("_cb_ip")&&Aa())}r.pSUPERFLY_video||(r.pSUPERFLY_video=[]);new bb;})();
